name = "slash-tv-relay"
main = "worker.js"
compatibility_date = "2026-07-01"

[[durable_objects.bindings]]
name = "RELAY_ROOM"
class_name = "RelayRoom"

[[durable_objects.bindings]]
name = "LEADERBOARD"
class_name = "Leaderboard"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RelayRoom"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["Leaderboard"]
